<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Classical Test Theory in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Full_Demo_files/libs/clipboard/clipboard.min.js"></script>
<script src="Full_Demo_files/libs/quarto-html/quarto.js"></script>
<script src="Full_Demo_files/libs/quarto-html/popper.min.js"></script>
<script src="Full_Demo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Full_Demo_files/libs/quarto-html/anchor.min.js"></script>
<link href="Full_Demo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Full_Demo_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Full_Demo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Full_Demo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Full_Demo_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#classical-test-theory-in-r-a-demonstration-of-item-analysis-packages" id="toc-classical-test-theory-in-r-a-demonstration-of-item-analysis-packages" class="nav-link active" data-scroll-target="#classical-test-theory-in-r-a-demonstration-of-item-analysis-packages">Classical Test Theory in R: A Demonstration of Item Analysis Packages</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#classical-test-theory-and-item-analysis" id="toc-classical-test-theory-and-item-analysis" class="nav-link" data-scroll-target="#classical-test-theory-and-item-analysis">Classical Test Theory and Item Analysis</a></li>
  <li><a href="#defining-item-analysis-terms" id="toc-defining-item-analysis-terms" class="nav-link" data-scroll-target="#defining-item-analysis-terms">Defining Item Analysis Terms</a></li>
  <li><a href="#software-in-item-analysis" id="toc-software-in-item-analysis" class="nav-link" data-scroll-target="#software-in-item-analysis">Software in Item Analysis</a></li>
  </ul></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a>
  <ul class="collapse">
  <li><a href="#loading-and-cleaning-data" id="toc-loading-and-cleaning-data" class="nav-link" data-scroll-target="#loading-and-cleaning-data">Loading and Cleaning Data</a></li>
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics">Summary Statistics</a></li>
  </ul></li>
  <li><a href="#demonstration" id="toc-demonstration" class="nav-link" data-scroll-target="#demonstration">Demonstration</a>
  <ul class="collapse">
  <li><a href="#ctt" id="toc-ctt" class="nav-link" data-scroll-target="#ctt"><em>CTT</em></a>
  <ul class="collapse">
  <li><a href="#load-package" id="toc-load-package" class="nav-link" data-scroll-target="#load-package">Load Package</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  </ul></li>
  <li><a href="#pysch" id="toc-pysch" class="nav-link" data-scroll-target="#pysch"><em>pysch</em></a>
  <ul class="collapse">
  <li><a href="#load-package-1" id="toc-load-package-1" class="nav-link" data-scroll-target="#load-package-1">Load Package</a></li>
  <li><a href="#results-1" id="toc-results-1" class="nav-link" data-scroll-target="#results-1">Results</a></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1">Interpretation</a></li>
  </ul></li>
  <li><a href="#itemanalysis" id="toc-itemanalysis" class="nav-link" data-scroll-target="#itemanalysis"><em>ItemAnalysis</em></a>
  <ul class="collapse">
  <li><a href="#load-package-2" id="toc-load-package-2" class="nav-link" data-scroll-target="#load-package-2">Load Package</a></li>
  <li><a href="#results-2" id="toc-results-2" class="nav-link" data-scroll-target="#results-2">Results</a></li>
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2">Interpretation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#comparison-and-recommendation" id="toc-comparison-and-recommendation" class="nav-link" data-scroll-target="#comparison-and-recommendation">Comparison and Recommendation</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Classical Test Theory in R</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Caroline Sutton Chubb and Hannah Scarbrough </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="classical-test-theory-in-r-a-demonstration-of-item-analysis-packages" class="level1">
<h1>Classical Test Theory in R: A Demonstration of Item Analysis Packages</h1>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<section id="classical-test-theory-and-item-analysis" class="level2">
<h2 class="anchored" data-anchor-id="classical-test-theory-and-item-analysis">Classical Test Theory and Item Analysis</h2>
<p>Classical Test Theory (CTT) states that the observed score, or the score a student receives on a test, is comprised of the raw score and a measure of random error (Traub, 1997). The foundation of CTT was established throughout the 1900’s and researchers have continued to expand on those principles (Urbina, 2014). CTT contrasts with Item Response Theory (IRT) in that CTT analyzes the whole test, rather than focusing on specific items and how individual test takers interact with the items.</p>
<p>Item analysis uses qualitative and quantitative methods to analyze items on a test. Quantitative methods use statistical analysis to evaluate the instruments for their difficulty, discrimination, and reliability (Urbina, 2014). Item analysis is one step in establishing the validity of a test. Item analysis is typically one of the last steps in the process of developing a test or questionnaire and conducted using pilot data (Artino et al., 2014). Through item analysis, test items are evaluated and added, modified, or removed and re-analyzed as needed to until the test is deemed satisfactory (Urbina, 2014). Ultimately, these processes should improve tests.</p>
</section>
<section id="defining-item-analysis-terms" class="level2">
<h2 class="anchored" data-anchor-id="defining-item-analysis-terms">Defining Item Analysis Terms</h2>
<p>Item analysis, as previously mentioned, several elements make up item analysis. These are defined below.</p>
<p><strong>Item difficulty</strong> indicates what proportion of test takers answer an item correctly and is commonly reported as the p value. A higher p value would signify the item is easier, while an item with a low p value would be more difficult.</p>
<p><strong>Item discrimination</strong> indicates how well an item can discriminate between low ability and high ability test takers based on the construct being studied. Discrimination is measured with a value between -1.00 and 1.00. A low value suggests that the item does not effectively discriminate between test takers while a negative value would indicate that the item inversely discriminates and should be eliminated in most cases.</p>
<p><strong>Item total correlation</strong> is the correlation of performance on a test with the total score. According to our lectures, negative values should indicate that the item is negatively related to other items and should therefore be discarded or revised.</p>
<p><strong>Reliability</strong> refers to the consistency of a measure but does not infer meaning or validity. This is typically measured using Cronbach’s Alpha, though other measures are increasing in popularity such as McDonald’s Omega. Reliability is necessary for a test to valid, but validity is not required for reliability. For example, test writers and administrators would want consistent results if they were to administer the test to the same group of people, multiple times. If there was a lot of variability in the results (outside of some normal error margin) the test would not be reliable and would need to be rewritten. This paper will use <em>Cronbach’s Alpha</em> (Chronbach, 1951) when discussing reliability.</p>
<p><strong>Validity</strong> refers to how well the test items accurately measure the purpose and intended use of the test and a test must be validated for each intended purpose of the test. For example, if the test is intended to measure math ability, but test questions required the taker to have knowledge of certain science concepts, the test would have low validity. Validity also refers to how test scores are interpreted. For example, a test designed for job aptitude, would not be valid for college admissions. Validation requires evidence collection to be statistically measured. According to the Standards for Education and Psychological Testing (2014), validity of the test is connected to the validity of the use of the test scores.&nbsp; This standard considers the scientific use of test and test validation. The argument is that validity is unitary – a combination of evidence or factors put together.&nbsp; That is, validity includes evidence on test content, response process, internal structures, and relations to other measures. This is a shift from previous definitions (before 2015), which determined different types of validity.</p>
</section>
<section id="software-in-item-analysis" class="level2">
<h2 class="anchored" data-anchor-id="software-in-item-analysis">Software in Item Analysis</h2>
<p>Different software is available to conduct this type of analysis, including SPSS, Microsoft Excel, SAS, and others (Gotzmann &amp; Bahry, 2012; Li, 2006). We particularly focus on R statistical programming (R Core Team, 2023), which is a free software used for computing and graphics.&nbsp; One of the many advantages of R is that it is free and open-source and uses packages to conduct different statistical analysis.</p>
<p>However, this open framework also means that there are many different options of packages and syntax used to conduct similar analysis, such as item analysis. While there are many R packages out there for conducting an item analysis, the specific functions and returned results are different and documentation outlining the formulas can be difficult to find. <strong>The purpose of this paper is to provide a demonstration of using item analysis in R, demonstrating its use with 3 different packages, and providing recommendations on what packages to use</strong>. &nbsp;</p>
</section>
</section>
<section id="dataset" class="level1">
<h1>Dataset</h1>
<p>The data we selected comes from a reasoning test administered to African American students in an urban setting. The test looks at general reasoning skills of children and their understanding about biology, and their understanding of biological phenomena, which is referred to as naïve biology (Waxman, Medin, &amp; Ross, 2007). The data was collected from 133 pre-school and pre-K students.&nbsp; For this demonstration, we focused on 16 questions relating to test-takers performance on an anthropocentric measure (<em>anthro)</em>.&nbsp; The questions are coded as dichotomous items, where 0 is not an anthropocentric response, and 1 is an anthropocentric response. A test takers total score would indicate how many items were correctly identified, for a total possible score of 16. Total scores are included in the dataset.</p>
<section id="loading-and-cleaning-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-and-cleaning-data">Loading and Cleaning Data</h2>
<p>Data was loaded and subset to include only the variables of focus (anthro_1 through anthro_16) using the <code>select()</code> function from the <em>tidyverse</em> package (Wickham et al., 2019). No re-coding or other steps were required to clean the data for this demonstration.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/ChildData_filtered_FINAL.csv"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>child_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">16</span><span class="sc">:</span><span class="dv">31</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># rename variables </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(child_data) <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">names</span>(child_data), <span class="cf">function</span>(x) {</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">grepl</span>(<span class="st">"anthro_"</span>, x)) {</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="st">"Item_"</span>, <span class="fu">gsub</span>(<span class="st">"anthro_"</span>, <span class="st">""</span>, x))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    x</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>child_data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(child_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="summary-statistics" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h2>
<p><code>describe()</code> is a function from the <em>psych</em> package, which will be used to demonstrate item analysis below. This was used to produce descriptive statistics to check the data. This function provides a table with a variety of descriptive statistics that are useful in evaluating test items.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(child_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        vars   n mean   sd median trimmed mad min max range  skew kurtosis   se
Item_1     1 131 0.64 0.48      1    0.68   0   0   1     1 -0.58    -1.67 0.04
Item_2     2 131 0.37 0.49      0    0.34   0   0   1     1  0.51    -1.75 0.04
Item_3     3 131 0.42 0.50      0    0.40   0   0   1     1  0.32    -1.91 0.04
Item_4     4 131 0.42 0.50      0    0.40   0   0   1     1  0.32    -1.91 0.04
Item_5     5 131 0.44 0.50      0    0.43   0   0   1     1  0.23    -1.96 0.04
Item_6     6 131 0.40 0.49      0    0.38   0   0   1     1  0.38    -1.87 0.04
Item_7     7 131 0.44 0.50      0    0.43   0   0   1     1  0.23    -1.96 0.04
Item_8     8 131 0.40 0.49      0    0.37   0   0   1     1  0.42    -1.84 0.04
Item_9     9 131 0.44 0.50      0    0.43   0   0   1     1  0.23    -1.96 0.04
Item_10   10 131 0.33 0.47      0    0.29   0   0   1     1  0.72    -1.49 0.04
Item_11   11 131 0.40 0.49      0    0.38   0   0   1     1  0.38    -1.87 0.04
Item_12   12 131 0.48 0.50      0    0.48   0   0   1     1  0.08    -2.01 0.04
Item_13   13 131 0.44 0.50      0    0.43   0   0   1     1  0.23    -1.96 0.04
Item_14   14 131 0.44 0.50      0    0.42   0   0   1     1  0.26    -1.95 0.04
Item_15   15 131 0.38 0.49      0    0.35   0   0   1     1  0.48    -1.78 0.04
Item_16   16 131 0.47 0.50      0    0.47   0   0   1     1  0.11    -2.00 0.04</code></pre>
</div>
</div>
</section>
</section>
<section id="demonstration" class="level1">
<h1>Demonstration</h1>
<p>We have selected <em>CTT</em> (Willse, 2018), <em>psych</em> (Revelle, 2023), and <em>itemanalysis</em> (Zopluoglu, 2022) packages in the R program (v4.3.2; R Core Team, 2023). The <em>CTT</em> package was selected by recommendation of peers, and it is frequently used to conduct basic CTT analyses. The <em>psych</em> package was selected for its frequent use and variety of functions in both CTT and IRT (Schumacker, 2019). The <em>itemanalysis</em> package was selected because it had been presented to the authors as a viable option during coursework.</p>
<p>While not covered in this demonstration, we are also aware of other packages, such as <em>psychometric</em>, <em>ICC</em>, as well as the CTT shiny app.</p>
<section id="ctt" class="level2">
<h2 class="anchored" data-anchor-id="ctt"><em>CTT</em></h2>
<section id="load-package" class="level3">
<h3 class="anchored" data-anchor-id="load-package">Load Package</h3>
<p>The CTT package was loaded using the <code>library()</code> function. The <code>itemAnalysis()</code> function, part of the <em>CTT</em> package, was used to produce the CTT analyses.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># if not previously installed, use install.packages()</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(CTT)</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(CTT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<p>In order to view all of the output produced by the <code>itemAnalysis()</code> function, the results need to be stored in an object using the <code>&lt;-</code> storage operator from Base R. In this example, we stored the results into an object called “IA.” This object is called again to produce the <strong>Cronbach’s Alpha</strong>, calculated with this package as 0.941.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>IA <span class="ot">&lt;-</span> <span class="fu">itemAnalysis</span>(child_data, <span class="at">itemReport=</span><span class="cn">TRUE</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>IA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Number of Items 
 16 

 Number of Examinees 
 131 

 Coefficient Alpha 
 0.941 </code></pre>
</div>
</div>
<p>By storing the output in an object, you then view the results for the test items separately, using the convention, ‘object_name$itemReport’ (in this example, IA$itemReport). This produces a table with four statistics for each test item including, item mean (<u><em>itemMean</em></u>), item total correlations (<em>pBis</em>), and the alpha value if the item were removed (alphaIfDeleted).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>IA<span class="sc">$</span>itemReport</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   itemName  itemMean      pBis       bis alphaIfDeleted
1    Item_1 0.6412214 0.2029702 0.2605267      0.9481337
2    Item_2 0.3740458 0.6868805 0.8772063      0.9377031
3    Item_3 0.4198473 0.6710367 0.8473024      0.9380656
4    Item_4 0.4198473 0.7631529 0.9636154      0.9359299
5    Item_5 0.4427481 0.6843411 0.8609339      0.9377603
6    Item_6 0.4045802 0.6723214 0.8516209      0.9380342
7    Item_7 0.4427481 0.7730790 0.9725704      0.9356855
8    Item_8 0.3969466 0.7056176 0.8954161      0.9372717
9    Item_9 0.4427481 0.7056319 0.8877187      0.9372653
10  Item_10 0.3282443 0.7959123 1.0342246      0.9353062
11  Item_11 0.4045802 0.7711305 0.9767811      0.9357543
12  Item_12 0.4809160 0.7196292 0.9022969      0.9369357
13  Item_13 0.4427481 0.7484584 0.9415965      0.9362643
14  Item_14 0.4351145 0.7377357 0.9291122      0.9365175
15  Item_15 0.3816794 0.6712748 0.8553223      0.9380559
16  Item_16 0.4732824 0.6746214 0.8462030      0.9379882</code></pre>
</div>
</div>
<p>While the <em>CTT</em> package does not identify item difficulty specifically, this information is provided via the mean. The item mean value is equal to the p value since there are only two possible responses (1 or 0). <em>CTT</em> also calculates the item total correlation which can be used to determine the discrimination index of each item.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>IA<span class="sc">$</span>itemReport[, <span class="fu">c</span>(<span class="st">"itemName"</span>,<span class="st">"itemMean"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   itemName  itemMean
1    Item_1 0.6412214
2    Item_2 0.3740458
3    Item_3 0.4198473
4    Item_4 0.4198473
5    Item_5 0.4427481
6    Item_6 0.4045802
7    Item_7 0.4427481
8    Item_8 0.3969466
9    Item_9 0.4427481
10  Item_10 0.3282443
11  Item_11 0.4045802
12  Item_12 0.4809160
13  Item_13 0.4427481
14  Item_14 0.4351145
15  Item_15 0.3816794
16  Item_16 0.4732824</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average difficulty </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(IA<span class="sc">$</span>itemReport[, <span class="fu">c</span>(<span class="st">"itemMean"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4332061</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>IA<span class="sc">$</span>itemReport[,<span class="fu">c</span>(<span class="st">"itemName"</span>,<span class="st">"pBis"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   itemName      pBis
1    Item_1 0.2029702
2    Item_2 0.6868805
3    Item_3 0.6710367
4    Item_4 0.7631529
5    Item_5 0.6843411
6    Item_6 0.6723214
7    Item_7 0.7730790
8    Item_8 0.7056176
9    Item_9 0.7056319
10  Item_10 0.7959123
11  Item_11 0.7711305
12  Item_12 0.7196292
13  Item_13 0.7484584
14  Item_14 0.7377357
15  Item_15 0.6712748
16  Item_16 0.6746214</code></pre>
</div>
</div>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>Looking at the table above, we are able to interpret item discrimination and item difficulty.</p>
<p>Item difficulty ranges from 0.33 to 0.64. The easiest item is Item 10 (p=0.328), and the hardest item is Item 1 (p=0.641). The average difficulty is 0.433, which would indicate an easy to moderate difficulty on the overall test.</p>
<p>For item correlation, negative values would indicate that the item is negatively related to other items and should be discarded or revised. Similarly, low values should also be investigated. Based on this data set, item correlation ranges from 0.20 to 0.796. There are no negative values, but Item 1 is relatively low, with a correlation of 0.20, suggesting that this item needs further investigation from a content expert.</p>
<p>Since this package does not specifically calculate discrimination, we infer discrimination by looking at correlation. We would determine that Item 1does not provide sufficient discrimination between test takers. Alternatively, Item 2 is a much better discriminator with a value of 0.69.</p>
</section>
</section>
<section id="pysch" class="level2">
<h2 class="anchored" data-anchor-id="pysch"><em>pysch</em></h2>
<section id="load-package-1" class="level3">
<h3 class="anchored" data-anchor-id="load-package-1">Load Package</h3>
<p>The <em>psych</em> package was loaded using the <code>library()</code> function of Base R.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This package was previously loaded to calculate the summary statistics. We repeat this step here specifically for item analysis</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># if not previously installed, use install.packages()</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(psych)</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="results-1" class="level3">
<h3 class="anchored" data-anchor-id="results-1">Results</h3>
<p>The function <code>alpha()</code> was used to produce a variety of statistics to review the reliability, difficulty, and discrimination of the test items. This function produces five tables of results, which will be described separately.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store results</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>alpha_results <span class="ot">&lt;-</span> <span class="fu">alpha</span>(child_data, <span class="at">warnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect different result outputs</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(alpha_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 15
 $ total        :'data.frame':  1 obs. of  9 variables:
  ..$ raw_alpha: num 0.941
  ..$ std.alpha: num 0.941
  ..$ G6(smc)  : num 0.954
  ..$ average_r: num 0.5
  ..$ S/N      : num 16
  ..$ ase      : num 0.00735
  ..$ mean     : num 0.433
  ..$ sd       : num 0.36
  ..$ median_r : num 0.533
 $ alpha.drop   :'data.frame':  16 obs. of  8 variables:
  ..$ raw_alpha: num [1:16] 0.948 0.938 0.938 0.936 0.938 ...
  ..$ std.alpha: num [1:16] 0.948 0.938 0.938 0.936 0.938 ...
  ..$ G6(smc)  : num [1:16] 0.959 0.951 0.951 0.947 0.95 ...
  ..$ average_r: num [1:16] 0.55 0.5 0.502 0.493 0.5 ...
  ..$ S/N      : num [1:16] 18.3 15 15.1 14.6 15 ...
  ..$ alpha se : num [1:16] 0.00669 0.00782 0.00778 0.00805 0.0078 ...
  ..$ var.r    : num [1:16] 0.00616 0.02452 0.02452 0.02279 0.0242 ...
  ..$ med.r    : num [1:16] 0.545 0.54 0.539 0.52 0.533 ...
 $ item.stats   :'data.frame':  16 obs. of  7 variables:
  ..$ n     : num [1:16] 131 131 131 131 131 131 131 131 131 131 ...
  ..$ raw.r : num [1:16] 0.282 0.73 0.717 0.798 0.729 ...
  ..$ std.r : num [1:16] 0.285 0.731 0.717 0.798 0.729 ...
  ..$ r.cor : num [1:16] 0.214 0.711 0.694 0.795 0.714 ...
  ..$ r.drop: num [1:16] 0.203 0.687 0.671 0.763 0.684 ...
  ..$ mean  : num [1:16] 0.641 0.374 0.42 0.42 0.443 ...
  ..$ sd    : num [1:16] 0.481 0.486 0.495 0.495 0.499 ...
 $ response.freq: num [1:16, 1:3] 0.359 0.626 0.58 0.58 0.557 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:16] "Item_1" "Item_2" "Item_3" "Item_4" ...
  .. ..$ : chr [1:3] "0" "1" "miss"
 $ keys         :List of 1
  ..$ : chr [1:16] "Item_1" "Item_2" "Item_3" "Item_4" ...
 $ scores       : num [1:131] 0.0625 0.0625 0.1875 0 0.9375 ...
 $ nvar         : int 16
 $ boot.ci      : NULL
 $ boot         : NULL
 $ feldt        :List of 4
  ..$ lower.ci:'data.frame':    1 obs. of  1 variable:
  .. ..$ raw_alpha: num 0.926
  ..$ alpha   :'data.frame':    1 obs. of  1 variable:
  .. ..$ raw_alpha: num 0.941
  ..$ upper.ci:'data.frame':    1 obs. of  1 variable:
  .. ..$ raw_alpha: num 0.955
  ..$ r.bar   :'data.frame':    1 obs. of  1 variable:
  .. ..$ raw_alpha: num 0.501
  ..- attr(*, "class")= chr [1:2] "psych" "alpha.ci"
 $ Unidim       :List of 1
  ..$ Unidim: num 0.884
 $ var.r        : num 0.0229
 $ Fit          :List of 1
  ..$ Fit.off: num 0.917
 $ call         : language alpha(x = child_data, warnings = FALSE)
 $ title        : NULL
 - attr(*, "class")= chr [1:2] "psych" "alpha"</code></pre>
</div>
</div>
<p>We first look at the frequencies of responses for each test item. For example, the frequency of correct responses for Item 1 is 0.64 or 64%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>alpha_results<span class="sc">$</span>response.freq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                0         1 miss
Item_1  0.3587786 0.6412214    0
Item_2  0.6259542 0.3740458    0
Item_3  0.5801527 0.4198473    0
Item_4  0.5801527 0.4198473    0
Item_5  0.5572519 0.4427481    0
Item_6  0.5954198 0.4045802    0
Item_7  0.5572519 0.4427481    0
Item_8  0.6030534 0.3969466    0
Item_9  0.5572519 0.4427481    0
Item_10 0.6717557 0.3282443    0
Item_11 0.5954198 0.4045802    0
Item_12 0.5190840 0.4809160    0
Item_13 0.5572519 0.4427481    0
Item_14 0.5648855 0.4351145    0
Item_15 0.6183206 0.3816794    0
Item_16 0.5267176 0.4732824    0</code></pre>
</div>
</div>
<p>The second table provides results for the set of test items as a whole. In this case <strong>Cronbach’s Alpha</strong> is calculated at 0.9414 (<em>raw_alpha</em>) and is described in the documentation as the “alpha based upon the covariances.” This table also provides the standardized alpha based on the correlations (<em>std.alpha</em>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>alpha_results<span class="sc">$</span>alpha.drop</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        raw_alpha std.alpha   G6(smc) average_r      S/N    alpha se
Item_1  0.9481337 0.9482022 0.9586651 0.5496287 18.30585 0.006688211
Item_2  0.9377031 0.9375159 0.9507438 0.5000680 15.00408 0.007817220
Item_3  0.9380656 0.9378838 0.9511096 0.5016422 15.09886 0.007777827
Item_4  0.9359299 0.9357561 0.9470429 0.4926549 14.56567 0.008051872
Item_5  0.9377603 0.9375672 0.9495838 0.5002867 15.01721 0.007804082
Item_6  0.9380342 0.9378505 0.9503933 0.5014995 15.09024 0.007778254
Item_7  0.9356855 0.9355326 0.9484193 0.4917272 14.51171 0.008092567
Item_8  0.9372717 0.9370835 0.9498825 0.4982286 14.89409 0.007872903
Item_9  0.9372653 0.9370975 0.9485260 0.4982877 14.89761 0.007867430
Item_10 0.9353062 0.9349839 0.9489770 0.4894627 14.38081 0.008124175
Item_11 0.9357543 0.9355618 0.9485750 0.4918481 14.51873 0.008069410
Item_12 0.9369357 0.9367605 0.9496989 0.4968620 14.81290 0.007917180
Item_13 0.9362643 0.9360968 0.9496760 0.4940749 14.64866 0.008012227
Item_14 0.9365175 0.9363459 0.9493364 0.4951180 14.70991 0.007974098
Item_15 0.9380559 0.9378817 0.9510319 0.5016330 15.09830 0.007784971
Item_16 0.9379882 0.9377945 0.9497669 0.5012592 15.07574 0.007770452
              var.r     med.r
Item_1  0.006161182 0.5451091
Item_2  0.024524340 0.5401858
Item_3  0.024515546 0.5391922
Item_4  0.022786349 0.5199251
Item_5  0.024200312 0.5332663
Item_6  0.023711671 0.5332663
Item_7  0.022742947 0.5256915
Item_8  0.024382894 0.5325132
Item_9  0.024184446 0.5332663
Item_10 0.023931371 0.5187677
Item_11 0.023239893 0.5325132
Item_12 0.024010821 0.5325132
Item_13 0.023864516 0.5199251
Item_14 0.023255550 0.5256915
Item_15 0.023780233 0.5358999
Item_16 0.024321355 0.5391922</code></pre>
</div>
</div>
<p>The table that provides most of the information is item.stats. Correlation is displayed in the <em>r.cor</em> column, which looks at the item whole correlation corrected for item overlap and scale reliability, and r.drop, which looks at item whole correlation corrected for item overlap and scale reliability. We can also see the mean (difficulty) of items. We infer discrimination by looking at the correlation of the item score against the total score on the exam.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>alpha_results<span class="sc">$</span>item.stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          n     raw.r     std.r     r.cor    r.drop      mean        sd
Item_1  131 0.2824976 0.2847149 0.2141744 0.2029702 0.6412214 0.4814833
Item_2  131 0.7301639 0.7308376 0.7114773 0.6868805 0.3740458 0.4857330
Item_3  131 0.7169870 0.7166677 0.6936944 0.6710367 0.4198473 0.4954283
Item_4  131 0.7979176 0.7975671 0.7945900 0.7631529 0.4198473 0.4954283
Item_5  131 0.7290352 0.7288690 0.7142788 0.6843411 0.4427481 0.4986182
Item_6  131 0.7178797 0.7179516 0.7007839 0.6723214 0.4045802 0.4926947
Item_7  131 0.8067676 0.8059181 0.7992541 0.7730790 0.4427481 0.4986182
Item_8  131 0.7471731 0.7473947 0.7314433 0.7056176 0.3969466 0.4911429
Item_9  131 0.7477982 0.7468636 0.7366826 0.7056319 0.4427481 0.4986182
Item_10 131 0.8249516 0.8263022 0.8173223 0.7959123 0.3282443 0.4713768
Item_11 131 0.8046845 0.8048293 0.7982073 0.7711305 0.4045802 0.4926947
Item_12 131 0.7603253 0.7596964 0.7451911 0.7196292 0.4809160 0.5015537
Item_13 131 0.7853241 0.7847845 0.7711298 0.7484584 0.4427481 0.4986182
Item_14 131 0.7758857 0.7753956 0.7653450 0.7377357 0.4351145 0.4976752
Item_15 131 0.7164993 0.7167498 0.6955383 0.6712748 0.3816794 0.4876634
Item_16 131 0.7206760 0.7201150 0.7047150 0.6746214 0.4732824 0.5012023</code></pre>
</div>
</div>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">Interpretation</h3>
<p>We compare these results with the CTT package for cross-validation, and achieve similar results/interpretations.</p>
<p>Looking at the Item Stat table, we find that the hardest item was Item 1 (p =0.64), and the easiest was Item 10 (p= 0.32). We see some discrepancy with the item correlation, but achieve similar results as seen in the previous package. <em>r.drop</em> is closest to <em>CTT’s</em> PBis values. We find that Item 1 is an outlier, and may need further investigation.</p>
</section>
</section>
<section id="itemanalysis" class="level2">
<h2 class="anchored" data-anchor-id="itemanalysis"><em>ItemAnalysis</em></h2>
<section id="load-package-2" class="level3">
<h3 class="anchored" data-anchor-id="load-package-2">Load Package</h3>
<p>The <em>itemanalysis</em> package was loaded using the <code>library()</code> function of Base R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(itemanalysis)</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(itemanalysis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="results-2" class="level3">
<h3 class="anchored" data-anchor-id="results-2">Results</h3>
<p>We create an object for the model, item.analysis, which primarily focused on the output called <em>item.stat</em>, which gives us a matrix of basic item statistics, such as item difficulty, item threshold, point-biserial, and biserial.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create key for dichotomous items</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>key <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"1"</span>,<span class="st">"1"</span>, <span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>,<span class="st">"1"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Create an object for the model </span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>item.analysis <span class="ot">&lt;-</span> <span class="fu">itemanalysis1</span>(<span class="at">data=</span>child_data, <span class="at">key=</span> key, <span class="at">options =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>), <span class="at">correction =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="at">span.par=</span>.<span class="dv">3</span>, <span class="at">verbose =</span> F)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>item.analysis<span class="sc">$</span>item.stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Item Difficulty Item Threshold Point-Biserial  Biserial
Item_1        0.6412214    -0.36172539      0.2029702 0.2605267
Item_2        0.3740458     0.32115675      0.6868805 0.8772063
Item_3        0.4198473     0.20228407      0.6710367 0.8473024
Item_4        0.4198473     0.20228407      0.7631529 0.9636154
Item_5        0.4427481     0.14400543      0.6843411 0.8609339
Item_6        0.4045802     0.24150943      0.6723214 0.8516209
Item_7        0.4427481     0.14400543      0.7730790 0.9725704
Item_8        0.3969466     0.26125855      0.7056176 0.8954161
Item_9        0.4427481     0.14400543      0.7056319 0.8877187
Item_10       0.3282443     0.44476644      0.7959123 0.9999000
Item_11       0.4045802     0.24150943      0.7711305 0.9767811
Item_12       0.4809160     0.04785468      0.7196292 0.9022969
Item_13       0.4427481     0.14400543      0.7484584 0.9415965
Item_14       0.4351145     0.16336761      0.7377357 0.9291122
Item_15       0.3816794     0.30107307      0.6712748 0.8553223
Item_16       0.4732824     0.06702113      0.6746214 0.8462030</code></pre>
</div>
</div>
<p>In our case, we are interested in looking at the column marked point-biserial. Point-biserial is a special case of the Pearson Correlation and is used when you want to measure the relationship between a continuous variable and a dichotomous variable, or one that has two values (Daines, 2023). This matches our dataset, which only includes 0 and 1, correct and incorrect responses. Krishnan (2013) argues that it can be used to assess item discrimination as it allows for an understanding of the relationship between the score on an item against the whole test. <em>Itemanalysis</em> package does not calculate the overall alpha.</p>
</section>
<section id="interpretation-2" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-2">Interpretation</h3>
<p>Our evaluation of this table is consistent with interpretations in the previous sections. There are no changes in our assessment of items.</p>
</section>
</section>
</section>
<section id="comparison-and-recommendation" class="level1">
<h1>Comparison and Recommendation</h1>
<p>While we would argue that you should be able to use one package to conduct item analysis, we find that this may not be the case. This can depend on the type of data you have (dichotomous tests or not), and what you are most interested in evaluating.&nbsp;For our demonstration, we were primarily concerned with 1. How easy the package is to use; 2. How much documentation is available; 3. How transparent are the calculations; and 4. How comprehensive are the outputs</p>
<p>Based on our criteria, we find that <em>psych</em> is the best package for several reasons. First, the help page is clear and defines all arguments needed. Documentation is also available online for the package, and it includes formulas used in development. And, while the outputs may be confusing and include more information than what it is needed for item analysis alone, they are comprehensive. With R, it is also possible to tailor those outputs for item analysis purposes only, as we did in our demonstration, by isolating the tables and columns we are most interested in. One limitation is that to use the psych package as we have, tailoring results, would require some experience coding in R and some theoretical knowledge on item analysis, since a lot of information is provided in the outputs.</p>
<p>Alternatively, <em>ItemAnalysis</em> and <em>CTT</em> are both very similar. In terms of ease of use, CTT is easiest. In <em>ItemAnalysis</em>, extra steps were necessary in the creation of keys for our dichotomous data sample, and mandatory arguments needed to be defined. These measures account for extra steps before running an analysis, and consequently, requires a greater understanding of how to code in R. Both packages are sparse in their documentation and definitions of terms. While documentation is provided for both, the <em>ItemAnalysis</em> is newer and does not include formulas. Their outputs are straightforward, and similar to one another, including measures for item difficulty and item correlation. Out of the two options, we would ultimately recommend <em>CTT</em> if <em>psych</em> was not a viable option.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Artino, A. R., La Rochelle, J. S., Dezee, K. J., &amp; Gehlbach, H. (2014). Developing questionnaires for educational research: AMEE Guide No.&nbsp;87. <em>Medical Teacher</em>, <em>36</em>(6), 463–474. https://doi.org/10.3109/0142159X.2014.889814</p>
<p>American Educational Research Association, American Psychological Association, &amp; National Council on Measurement in Education (Eds.). (2014).&nbsp;<em>Standards for educational and psychological testing</em>. American Educational Research Association.</p>
<p>Cronbach, L. J. (1951). Coefficient alpha and the internal structure of tests. <em>Psychometrika</em>. <em>Springer Science and Business Media LLC,16</em> (3), 297–334.</p>
<p>Gotzmann, A., &amp; Bahry, L. M. (2012). Review of “jMetrik.” <em>Journal of Research &amp; Practice in Assessment</em>. https://www.rpajournal.com/review-of-jmetrik/</p>
<p>Li, Y. (2006). Using the open-source statistical language R to analyze the dichotomous Rasch model. <em>Behavior Research Methods</em>, <em>38</em>(3), 532–541. https://doi.org/10.3758/BF03192809</p>
<p>Schumacker, R. (2019). Psychometric Packages in R. <em>Measurement: Interdisciplinary Research and Perspectives</em>, <em>17</em>(2), 106–112. https://doi.org/10.1080/15366367.2018.1544434</p>
<p>R Core Team (2023). <em>R: A Language and Environment for Statistical Computing</em>. R&nbsp; Foundation for Statistical Computing, Vienna, Austria. &lt;https://www.R-project.org/&gt;.</p>
<p>Revelle, W. (2023).&nbsp;<em>psych: Procedures for Psychological, Psychometric, and Personality Research</em>. Northwestern University, Evanston, Illinois. R package version 2.3.9,&nbsp;<a href="https://cran.r-project.org/package=psych">https://CRAN.R-project.org/package=psych</a>.</p>
<p>Traub, R. E. (1997). Classical Test Theory in Historical Perspective. <em>Educational Measurement: Issues and Practice</em>, <em>16</em>(4), 8–14.</p>
<p>Urbina, S. (2014). <em>Essentials of psychological testing</em> (Second edition.). Wiley.</p>
<p>Waxman, S., Medin, D., &amp; Ross, N. (2007). Folkbiological reasoning from a cross-cultural developmental perspective: early essentialist notions are shaped by cultural beliefs. Developmental Psychology, 43(2), 294-308. doi: 10.1037/0012-1649.43.2.294</p>
<p>Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019). “Welcome to the tidyverse.” Journal of Open Source Software, 4(43), 1686. doi:10.21105/joss.01686.</p>
<p>Willse JT (2018). _CTT: Classical Test Theory Functions_. R package version 2.3.3, &lt;https://CRAN.R-project.org/package=CTT&gt;.</p>
<p>Zopluoglu, C (2022). <em>itemanalysis: Classical Test Theory Item Analysis</em>. R package version 1.1, https://CRAN.R-project.org/package=itemanalysis&gt;.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>